version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      - API_KEY=$API_KEY
      - DOMAIN=$DOMAIN
      - SENDER=$SENDER
    ports:
      - "3333:3030"
